services:
  librespeed:
    build:
      network: host
      context: ./librespeed
      args:
        speedtest_cli_version: 1.0.11
        librespeed_exporter_version: 0.4.0
    ports:
      - 192.168.1.1:51423:51423
    dns:
      - 192.168.1.2
    hostname: librespeed
    cap_drop:
      - ALL
    networks:
      - librespeed
    restart: always

  influxdb:
    image: influxdb:1.8
    environment:
      INFLUXDB_REPORTING_DISABLED: 'true'
    ports:
      - 192.168.1.1:8086:8086
    dns:
      - 192.168.1.2
    hostname: influxdb
    volumes:
      - type: volume
        source: influxdb_data
        target: /var/lib/influxdb
      - type: bind
        source: ./influxdb/init_db.iql
        target: /docker-entrypoint-initdb.d/init_db.iql
    cap_drop:
      - ALL
    user: influxdb
    networks:
      - librespeed
    restart: always

  prometheus:
    image: prom/prometheus:v2.55.1
    ports:
      - 192.168.1.1:9090:9090
    dns:
      - 192.168.1.2
    hostname: prometheus
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: volume
        source: prometheus_data
        target: /prometheus/
    depends_on:
      - librespeed
      - influxdb
    cap_drop:
      - ALL
    networks:
      - librespeed
    restart: always

  grafana:
    image: grafana/grafana:11.3.2
    environment:
      GF_ANALYTICS_REPORTING_ENABLED: false
      GF_ANALYTICS_CHECK_FOR_UPDATES: false
      GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: false
    ports:
      - 192.168.1.1:3000:3000
    dns:
      - 192.168.1.2
    hostname: grafana
    volumes:
      - type: volume
        source: grafana_data
        target: /var/lib/grafana
    depends_on:
      - prometheus
    cap_drop:
      - ALL
    networks:
      - librespeed
    restart: always

volumes:
  prometheus_data:
  grafana_data:
  influxdb_data:

networks:
  librespeed:
