version: '3.8'

services:
  librespeed:
    build:
      network: host
      context: ./librespeed
      args:
        librespeed_version: 1.0.10
    command:
      - '51423'
    ports:
      - 51423:51423
    dns:
      - 192.168.1.2
    hostname: librespeed
    cap_drop:
      - ALL
    networks:
      - librespeed

  prometheus:
    image: prom/prometheus:v2.48.1
    ports:
      - 9090:9090
    dns:
      - 192.168.1.2
    hostname: prometheus
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: volume
        source: prometheus_data
        target: /prometheus/
    depends_on:
      - librespeed
    cap_drop:
      - ALL
    networks:
      - librespeed

  grafana:
    image: grafana/grafana:10.1.6
    ports:
      - 3000:3000
    dns:
      - 192.168.1.2
    hostname: grafana
    volumes:
      - type: volume
        source: grafana_data
        target: /var/lib/grafana
    depends_on:
      - prometheus
    cap_drop:
      - ALL
    networks:
      - librespeed

volumes:
  prometheus_data:
  grafana_data:
networks:
  librespeed:
